name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.Acessid2 }}
          aws-secret-access-key: ${{ secrets.Keysecrets2 }}
          aws-region: us-west-2

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
          bucket: resume-web-bucket
          aws-access-key-id: ${{ secrets.Accessid2 }}
          aws-secret-access-key: ${{ secrets.Keysecrets2 }}
          aws-region: us-east-1

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ELQP6ZSJS6Z80 --paths "/*"
