name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TBD }}  # replace with your actual secret name
          aws-secret-access-key: ${{ secrets.Key }}  # replace with your actual secret name
          aws-region: us-east-1

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete --exclude '.git/*'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TBD }}  # replace with your actual secret name
          AWS_SECRET_ACCESS_KEY: ${{ secrets.Key }}  # replace with your actual secret name
          AWS_REGION: 'us-east-1'
          AWS_S3_BUCKET: ${{ secrets.Bucket }}  # replace with your actual secret name

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ELQP6ZSJS6Z80 --paths "/*"
