name: 'Terraform GitHub Actions'
on:
  push:
    branches:
      - main
env:
  TF_VERSION: 'latest'
  TF_CLI_ARGS: '-no-color'
  AWS_REGION: 'us-east-1'  # Update this if you're using a different AWS region

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Terraform Setup'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AccessID }}
          aws-secret-access-key: ${{ secrets.Keysecrets }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Validate'
        run: terraform validate ${{ env.TF_CLI_ARGS }}

      # Removed the Python steps

      - name: 'Terraform Plan'
        run: terraform plan ${{ env.TF_CLI_ARGS }}

      - name: 'Terraform Apply'
        run: terraform apply ${{ env.TF_CLI_ARGS }} -auto-approve
